
package com.processcentric.motivationalsentences.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.storageservice.person.ws.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCentricMotivationalSentencesModel", targetNamespace = "http://ws.motivationalsentences.processcentric.com/")
@XmlSeeAlso({
    com.processcentric.motivationalsentences.ws.ObjectFactory.class,
    com.storageservice.person.ws.ObjectFactory.class
})
public interface ProcessCentricMotivationalSentencesModel {


    /**
     * 
     * @param lng
     * @param lat
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "dailymotivationalWeatherCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.DailymotivationalWeatherCalls")
    @ResponseWrapper(localName = "dailymotivationalWeatherCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.DailymotivationalWeatherCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/dailymotivationalWeatherCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/dailymotivationalWeatherCallsResponse")
    public String dailymotivationalWeatherCalls(
        @WebParam(name = "lat", targetNamespace = "")
        String lat,
        @WebParam(name = "lng", targetNamespace = "")
        String lng);

    /**
     * 
     * @param startDate
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @param idPerson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBaseOnBmiStatusCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBaseOnBmiStatusCalls")
    @ResponseWrapper(localName = "motivationBaseOnBmiStatusCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBaseOnBmiStatusCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBaseOnBmiStatusCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBaseOnBmiStatusCallsResponse")
    public String motivationBaseOnBmiStatusCalls(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @param idPerson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "dailymotivationalCaloriesCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.DailymotivationalCaloriesCalls")
    @ResponseWrapper(localName = "dailymotivationalCaloriesCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.DailymotivationalCaloriesCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/dailymotivationalCaloriesCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/dailymotivationalCaloriesCallsResponse")
    public String dailymotivationalCaloriesCalls(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param startDate
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @param idPerson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedOnBmiValueDifferenceCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnBmiValueDifferenceCalls")
    @ResponseWrapper(localName = "motivationBasedOnBmiValueDifferenceCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnBmiValueDifferenceCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnBmiValueDifferenceCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnBmiValueDifferenceCallsResponse")
    public String motivationBasedOnBmiValueDifferenceCalls(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param startDate
     * @param accessToken
     * @param userId
     * @param endDate
     * @param refreshToken
     * @param idPerson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedOnWeightDifferenceCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnWeightDifferenceCalls")
    @ResponseWrapper(localName = "motivationBasedOnWeightDifferenceCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnWeightDifferenceCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnWeightDifferenceCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnWeightDifferenceCallsResponse")
    public String motivationBasedOnWeightDifferenceCalls(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "startDate", targetNamespace = "")
        String startDate,
        @WebParam(name = "endDate", targetNamespace = "")
        String endDate,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedOnGoalStepsCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnGoalStepsCalls")
    @ResponseWrapper(localName = "motivationBasedOnGoalStepsCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnGoalStepsCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnGoalStepsCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnGoalStepsCallsResponse")
    public String motivationBasedOnGoalStepsCalls(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedOnFavouriteActivitiesCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnFavouriteActivitiesCalls")
    @ResponseWrapper(localName = "motivationBasedOnFavouriteActivitiesCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnFavouriteActivitiesCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnFavouriteActivitiesCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnFavouriteActivitiesCallsResponse")
    public String motivationBasedOnFavouriteActivitiesCalls(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param idPerson
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedOnGoalAchievedLevelCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnGoalAchievedLevelCalls")
    @ResponseWrapper(localName = "motivationBasedOnGoalAchievedLevelCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedOnGoalAchievedLevelCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnGoalAchievedLevelCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedOnGoalAchievedLevelCallsResponse")
    public String motivationBasedOnGoalAchievedLevelCalls(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson);

    /**
     * 
     * @param lng
     * @param lat
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "motivationBasedonForecastCalls", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedonForecastCalls")
    @ResponseWrapper(localName = "motivationBasedonForecastCallsResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.MotivationBasedonForecastCallsResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedonForecastCallsRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/motivationBasedonForecastCallsResponse")
    public String motivationBasedonForecastCalls(
        @WebParam(name = "lat", targetNamespace = "")
        String lat,
        @WebParam(name = "lng", targetNamespace = "")
        String lng);

    /**
     * 
     * @param person
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "registration", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.Registration")
    @ResponseWrapper(localName = "registrationResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.RegistrationResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/registrationRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/registrationResponse")
    public int registration(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

    /**
     * 
     * @param email
     * @param password
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "idPerson", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.LoginResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/loginRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/loginResponse")
    public int login(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param refreshToken
     * @param idPerson
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "sentence", targetNamespace = "")
    @RequestWrapper(localName = "verifyAndIncrementDailyGoalAchieved", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.VerifyAndIncrementDailyGoalAchieved")
    @ResponseWrapper(localName = "verifyAndIncrementDailyGoalAchievedResponse", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", className = "com.processcentric.motivationalsentences.ws.VerifyAndIncrementDailyGoalAchievedResponse")
    @Action(input = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/verifyAndIncrementDailyGoalAchievedRequest", output = "http://ws.motivationalsentences.processcentric.com/ProcessCentricMotivationalSentencesModel/verifyAndIncrementDailyGoalAchievedResponse")
    public int verifyAndIncrementDailyGoalAchieved(
        @WebParam(name = "idPerson", targetNamespace = "")
        int idPerson,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "user_id", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh_token", targetNamespace = "")
        String refreshToken);

}
