
package com.processcentric.motivationalsentences.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "processCentricMotivationalSentencesService", targetNamespace = "http://ws.motivationalsentences.processcentric.com/", wsdlLocation = "https://processcentricsentences.herokuapp.com/ws/processCentircMotivationalSentences?wsdl")
public class ProcessCentricMotivationalSentencesService
    extends Service
{

    private final static URL PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_EXCEPTION;
    private final static QName PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_QNAME = new QName("http://ws.motivationalsentences.processcentric.com/", "processCentricMotivationalSentencesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://processcentricsentences.herokuapp.com/ws/processCentircMotivationalSentences?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_WSDL_LOCATION = url;
        PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_EXCEPTION = e;
    }

    public ProcessCentricMotivationalSentencesService() {
        super(__getWsdlLocation(), PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_QNAME);
    }

    public ProcessCentricMotivationalSentencesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_QNAME, features);
    }

    public ProcessCentricMotivationalSentencesService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_QNAME);
    }

    public ProcessCentricMotivationalSentencesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_QNAME, features);
    }

    public ProcessCentricMotivationalSentencesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessCentricMotivationalSentencesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessCentricMotivationalSentencesModel
     */
    @WebEndpoint(name = "ProcessCentricMotivationalSentencesImplPort")
    public ProcessCentricMotivationalSentencesModel getProcessCentricMotivationalSentencesImplPort() {
        return super.getPort(new QName("http://ws.motivationalsentences.processcentric.com/", "ProcessCentricMotivationalSentencesImplPort"), ProcessCentricMotivationalSentencesModel.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessCentricMotivationalSentencesModel
     */
    @WebEndpoint(name = "ProcessCentricMotivationalSentencesImplPort")
    public ProcessCentricMotivationalSentencesModel getProcessCentricMotivationalSentencesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.motivationalsentences.processcentric.com/", "ProcessCentricMotivationalSentencesImplPort"), ProcessCentricMotivationalSentencesModel.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_EXCEPTION!= null) {
            throw PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_EXCEPTION;
        }
        return PROCESSCENTRICMOTIVATIONALSENTENCESSERVICE_WSDL_LOCATION;
    }

}
