
package com.processcentric.goal.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProcessCentricGoal", targetNamespace = "http://ws.goal.processcentric.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessCentricGoal {


    /**
     * 
     * @param accessToken
     * @param userId
     * @param personId
     * @param refresh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentenceDistance", targetNamespace = "")
    @RequestWrapper(localName = "checkDistance", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckDistance")
    @ResponseWrapper(localName = "checkDistanceResponse", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckDistanceResponse")
    @Action(input = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkDistanceRequest", output = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkDistanceResponse")
    public String checkDistance(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param personId
     * @param refresh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentenceWeight", targetNamespace = "")
    @RequestWrapper(localName = "checkWeight", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckWeight")
    @ResponseWrapper(localName = "checkWeightResponse", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckWeightResponse")
    @Action(input = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkWeightRequest", output = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkWeightResponse")
    public String checkWeight(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param personId
     * @param refresh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentenceSteps", targetNamespace = "")
    @RequestWrapper(localName = "checkSteps", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckSteps")
    @ResponseWrapper(localName = "checkStepsResponse", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckStepsResponse")
    @Action(input = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkStepsRequest", output = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkStepsResponse")
    public String checkSteps(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh);

    /**
     * 
     * @param accessToken
     * @param userId
     * @param personId
     * @param refresh
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sentenceCalories", targetNamespace = "")
    @RequestWrapper(localName = "checkCalories", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckCalories")
    @ResponseWrapper(localName = "checkCaloriesResponse", targetNamespace = "http://ws.goal.processcentric.com/", className = "com.processcentric.goal.ws.CheckCaloriesResponse")
    @Action(input = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkCaloriesRequest", output = "http://ws.goal.processcentric.com/ProcessCentricGoal/checkCaloriesResponse")
    public String checkCalories(
        @WebParam(name = "personId", targetNamespace = "")
        int personId,
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken,
        @WebParam(name = "userId", targetNamespace = "")
        String userId,
        @WebParam(name = "refresh", targetNamespace = "")
        String refresh);

}
