
package com.processcentric.goal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "processCentricServiceGoal", targetNamespace = "http://ws.goal.processcentric.com/", wsdlLocation = "https://processcentricgoals.herokuapp.com/ws/businessLogicServiceGoal?wsdl")
public class ProcessCentricServiceGoal
    extends Service
{

    private final static URL PROCESSCENTRICSERVICEGOAL_WSDL_LOCATION;
    private final static WebServiceException PROCESSCENTRICSERVICEGOAL_EXCEPTION;
    private final static QName PROCESSCENTRICSERVICEGOAL_QNAME = new QName("http://ws.goal.processcentric.com/", "processCentricServiceGoal");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://processcentricgoals.herokuapp.com/ws/businessLogicServiceGoal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSCENTRICSERVICEGOAL_WSDL_LOCATION = url;
        PROCESSCENTRICSERVICEGOAL_EXCEPTION = e;
    }

    public ProcessCentricServiceGoal() {
        super(__getWsdlLocation(), PROCESSCENTRICSERVICEGOAL_QNAME);
    }

    public ProcessCentricServiceGoal(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSCENTRICSERVICEGOAL_QNAME, features);
    }

    public ProcessCentricServiceGoal(URL wsdlLocation) {
        super(wsdlLocation, PROCESSCENTRICSERVICEGOAL_QNAME);
    }

    public ProcessCentricServiceGoal(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSCENTRICSERVICEGOAL_QNAME, features);
    }

    public ProcessCentricServiceGoal(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessCentricServiceGoal(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessCentricGoal
     */
    @WebEndpoint(name = "ProcessCentricGoalImplPort")
    public ProcessCentricGoal getProcessCentricGoalImplPort() {
        return super.getPort(new QName("http://ws.goal.processcentric.com/", "ProcessCentricGoalImplPort"), ProcessCentricGoal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessCentricGoal
     */
    @WebEndpoint(name = "ProcessCentricGoalImplPort")
    public ProcessCentricGoal getProcessCentricGoalImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.goal.processcentric.com/", "ProcessCentricGoalImplPort"), ProcessCentricGoal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSCENTRICSERVICEGOAL_EXCEPTION!= null) {
            throw PROCESSCENTRICSERVICEGOAL_EXCEPTION;
        }
        return PROCESSCENTRICSERVICEGOAL_WSDL_LOCATION;
    }

}
